name: matcher
version: 0.1.0.0
github: "githubuser/matcher"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/matcher#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - QuickCheck
  - text
  - aeson
  - bytestring
  - vector
  - scientific
  - utf8-string
  - data-fix
  - twain
  - warp
  - transformers
  - recursion-schemes
  - template-haskell
  - th-abstraction
  - comonad
  - hspec
  - regex-tdfa ^>= 1.3.2
  - transformers
  - mongoDB
  - bson
  - attoparsec
  - unordered-containers
  - hedis
  - async

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  matcher-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - matcher

tests:
  matcher-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - matcher
